version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jamesrweb"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "jamesrweb"
    labels:
      - "elm"
      - "dependencies"
